#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker41"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "b3cc666bc1e04566b2b974a2fb9c5f08" }
]

[assets]
directory = "./public"
